// 'use strict';
// alert('Я JavaScript!');
// let ourPlanetName = 'Земля';
// let currentUserName = 'Лазиз';
// const BIRTHDAY = '01.03.1995';
// const age = '27';
// let myName = 'Laziz';
// const myAge = '27';
// const myBIRTHDAY = '01.03.1995';
// alert(`Hello ${myName}`);
// alert(`My age ${myAge}`);
// alert(`My birthday ${myBIRTHDAY}`);
// 'use strict';
// let x = 1;
// x = -x;
// alert(x);
// 'use strict';
// let x = 1;
// let y = 3;
// alert(y - x);
// alert(5 % 2);
// alert(2 ** 5);
// alert(4 ** 1 / 2);
// let s = 'my' + ' name';
// alert(s);
// alert(6 - '2');
// alert(6 / '2');
// let apples = '3';
// let bananas = '4';
// alert(+apples + +bananas);
// 'use strict';
// let x = 2 * 2 + 1;
// alert(x);
// 'use strict';
// let a = 1;
// let b = 2;
// let c = 3 - (a = b + 1);
// alert(a); // 3
// alert(c); // 0
// 'use strict';
// let a = 2;
// a += 5;
// a *= 2;
// alert(a);
// let a = 2;
// a *= 3 + 5;
// alert(a);
// 'use strict';
// let a = 2;
// a++;
// alert(a);
// 'use strict';
// let a = 1;
// // alert(2 * a);
// a++;
// alert(a);
